#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    02                                                 :+:    :+:             #
#                                                      +:+                     #
#    By: mlokhors <mlokhors@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2019/10/05 11:33:53 by mlokhors       #+#    #+#                 #
#    Updated: 2019/10/05 11:33:53 by mlokhors      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

echo "Type which user to delete, followed by [ENTER]:"

read user

pkill -fu $user
userdel -fr $user