#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    03                                                 :+:    :+:             #
#                                                      +:+                     #
#    By: mlokhors <mlokhors@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2019/10/05 11:34:03 by mlokhors       #+#    #+#                 #
#    Updated: 2019/10/05 11:34:03 by mlokhors      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

echo "ROCK PAPER SCISSORS.......(capital letters)"

read hand

RANDOM=$(($RANDOM % 3))
echo "$random"

if [[ $RANDOM == 0 && $hand == 'ROCK' ]];
then
    echo "YOU WON"
elif [[ $RANDOM == 1 && $hand == 'PAPER' ]];
then 
    echo "YOU WON"
elif [[ $RANDOM == 2 && $hand == 'SCICCORS' ]];   
then 
    echo "YOU WON"
else
    echo "YOU LOSS"
fi